name: Fetch Gold Rate Daily

on:
  schedule:
    - cron: '30 07 * * *'  # Runs daily at 07:30 UTC = 13:00 IST (01:00 PM)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas matplotlib

    - name: Run script
      run: python fetch_gold_rate.py

    - name: Generate graph
      run: python generate_graph.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT_TOKEN }}@github.com/${{ github.repository }}
        git add gold_rates.csv gold_trend.png
        git commit -m "Update gold rate and chart" || echo "No changes to commit"
        git push origin HEAD:main
