name: Fetch Gold Rate Daily

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Run script
      run: python fetch_gold_rate.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT_TOKEN }}@github.com/${{ github.repository }}
        git add gold_rates.csv
        git commit -m "Update gold rate" || echo "No changes to commit"
        git push origin HEAD:tmp_main_selenium
